language: python
python:
  - "2.7"
# install system dependencies
before_install:
  - apt-get install build-essential
  - apt-get install libhdf5-serial-dev
# install Python dependencies
install: "pip install -r requirements.txt"
script: python tests/run.py
