language: python
python:
  - "2.7"
# install system dependencies
before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install libnetcdf-dev
  - sudo apt-get remove libcurl4-openssl-dev
  - sudo apt-get install libcurl3-gnutls
# install Python dependencies
install: "pip -v install -r requirements.txt"
script: python tests/run.py
